from langchain.agents import create_agent
from langchain_core.messages import SystemMessage
from langchain_core.messages.human import HumanMessage

from config import llm_model
from state import AgentState

analysis_system_prompt = """
You are a Deep Analysis AI agent.

Your job is to carefully analyze information gathered from search tools and the existing summary produced by another model.

You will receive:
1. Searched Documents – raw information retrieved from external sources.
2. A Summary – a preliminary summary generated by another AI.

Your task is to perform deep reasoning and produce a high-quality analytical response.

Instructions:

1. Carefully read all documents and the provided summary.
2. Verify whether the summary accurately reflects the information in the documents.
3. Identify:
   - Missing important information
   - Incorrect or misleading statements
   - Contradictions between sources
4. Extract the most important facts and insights from the documents.
5. Combine the verified information into a clear, logically structured explanation.
6. If documents contain conflicting information, explain the conflict and give the most reliable interpretation.
7. Focus on reasoning and insight rather than repeating the text.
8. Do not hallucinate information that is not present in the documents.

Output Format:

Final Analysis:
- Core Insights
- Key Supporting Evidence
- Corrections to the Summary (if any)
- Additional Important Information
- Final Conclusion

Keep the analysis clear, concise, and evidence-based.
"""


def deep_analysis_agent(state: AgentState):
    """This is deep analysis agent"""
    analysis_agent = create_agent(model=llm_model)
    context = (
        f"""searched documents: {state["documents"]} ,summary:{state["summary"]}"""
    )
    payload = {
        "messages": [SystemMessage(analysis_system_prompt), HumanMessage(context)]
    }
    res = analysis_agent.invoke(payload)
    return {"insights": res["messages"][-1].content}
